acls:
  user_naming_info:
    label: 'usernaming.security.user_naming_info.label'
    description: 'usernaming.security.user_naming_info.description'
    type: action
    group_name: ""
    category: "account_management"
