services:
  user_naming.importexport.data_converter:
    parent: oro_importexport.data_converter.configurable

  user_naming.importexport.strategy.tax.add_or_replace:
    parent: oro_importexport.strategy.configurable_add_or_replace

  user_naming.importexport.processor.export:
    parent: oro_importexport.processor.export_abstract
    calls:
      - [setDataConverter, ['@user_naming.importexport.data_converter']]
    tags:
      - name: oro_importexport.processor
        type: export
        entity: Training\Bundle\UserNamingBundle\Entity\UserNamingType
        alias: user_naming_type

  user_naming.importexport.processor.import:
    parent: oro_importexport.processor.import_abstract
    calls:
      - [setDataConverter, ['@user_naming.importexport.data_converter']]
    tags:
      - name: oro_importexport.processor
        type: import
        entity: Training\Bundle\UserNamingBundle\Entity\UserNamingType
        alias: user_naming_type

  user_naming.importexport.template_fixture.user_naming_type:
    class: Training\Bundle\UserNamingBundle\ImportExport\TemplateFixture\UserNamingTypeFixture
    tags:
      - { name: oro_importexport.template_fixture }

  user_naming.importexport.configuration_provider.user_naming_type:
    class: Training\Bundle\UserNamingBundle\ImportExport\Configuration\UserNamingTypeImportExportConfigurationProvider
    arguments:
      - '@translator'
    tags:
      - { name: oro_importexport.configuration, alias: user_naming }

  # Fixtures
  user_naming.importexport.data_converter.template_fixture.user_naming_type:
    parent: oro_importexport.data_converter.template_fixture.configurable

  user_naming.importexport.processor.export_template.user_naming_type:
    parent: oro_importexport.processor.export_abstract
    calls:
      - [ setDataConverter, [ '@user_naming.importexport.data_converter.template_fixture.user_naming_type' ] ]
    tags:
      - name: oro_importexport.processor
        type: export_template
        entity: Training\Bundle\UserNamingBundle\Entity\UserNamingType
        alias: user_naming_type
